export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_ATTEMPT = 'GET_USER_DATA_ATTEMPT';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';
